# thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template: true
    enabled: true
    cache: false
# druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sam?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: root
# Redis
  redis:
    host: 192.168.153.129
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 3000ms
    timeout: 3000ms

# mybatis
mybatis:
  type-aliases-package: com.zhousz.ms.dao
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:/mapping/*.xml
# port
server:
  port: 8081
