package com.zhousz.ms.dao;

import com.zhousz.ms.domain.MsUser;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface MsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated
     */
    int insert(MsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated
     */
    int insertSelective(MsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated
     */
    MsUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MsUser record);
}